### PR TITLE
New database unit tests

### PR DESCRIPTION
**Pull request by connie**
This addresses https://github.com/GreenGroup/RMG-database/issues/65

- Makes sure that rule entries are in the correct order like the family's top template.  
- Makes sure that the top templates are defined with products and reactants named differently if the family is not its own reverse.

### CODE REVIEW

**Comment by rwest** [comment]
How about a more general "no two nodes in the family (in any tree) can have the same label"?

**Comment by connie** [comment]
That test already exists I think, and we have a check to make sure that the entries don't have identical names when we load it.  This one is only for the product template groups to ensure that they don't overwrite an existing group.

**Comment by rwest** [comment]
How come the previous test didn't catch this then? I thought the problem was that the name was reused? Or am I confused?

**Comment by connie** [comment]
We do the test for all the entries inside groups.py, but we don't check this part of it:

    template(reactants=["XSYJ"], products=["XYSJ"], ownReverse=False)

**Pull request merged**
