### PR TITLE
moving KineticsDatabase to rmgpy.data.kinetics.base from __init__

### PR DESCRIPTION
**Pull request by nickvandewiele**
The goal is to remove stuff from __init__ as much as possible.

- moved KineticsDatabase to a new module 'database' in rmgpy.data.kinetics
- updated imports in RMG-Py.
- replaced import * statements by specific classes.
- moved all import statements to the top.
- replaced a relative import (from kinetics) by an absolute one.

### CODE REVIEW

**Comment by enochd** [comment]
seems like travis build failed: `ERROR: Test that the loadFamilies function raises the correct exceptions`

**Comment by rwest** [comment]
Would be nice if you could get rid of (some of) the `from foo import *` statements in `rmgpy/rmg/model.py` while you're at it. Better to explicitly import only the things we need.

**Comment by rwest** [comment]
Something is up with `deepcopy` in `rmgpy/data/solvation.py` according to the Travis test

```python
======================================================================
ERROR: Test we can estimate solvation thermochemistry.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GreenGroup/RMG-Py/rmgpy/data/solvationTest.py", line 110, in testCorrectionGeneration
    soluteData = self.database.getSoluteData(species)
  File "/home/travis/build/GreenGroup/RMG-Py/rmgpy/data/solvation.py", line 589, in getSoluteData
    soluteData = self.getSoluteDataFromLibrary(species, self.libraries['solute'])
  File "/home/travis/build/GreenGroup/RMG-Py/rmgpy/data/solvation.py", line 637, in getSoluteDataFromLibrary
    return (deepcopy(entry.data), library, entry)
NameError: global name 'deepcopy' is not defined
======================================================================
ERROR: Test that for a given solvent viscosity and temperature we can calculate a solute's diffusivity
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GreenGroup/RMG-Py/rmgpy/data/solvationTest.py", line 57, in testDiffusivity
    soluteData = self.database.getSoluteData(species)
  File "/home/travis/build/GreenGroup/RMG-Py/rmgpy/data/solvation.py", line 589, in getSoluteData
    soluteData = self.getSoluteDataFromLibrary(species, self.libraries['solute'])
  File "/home/travis/build/GreenGroup/RMG-Py/rmgpy/data/solvation.py", line 637, in getSoluteDataFromLibrary
    return (deepcopy(entry.data), library, entry)
NameError: global name 'deepcopy' is not defined
======================================================================
ERROR: Test we can calculate and set the McGowan volume for species containing H,C,O,N or S
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GreenGroup/RMG-Py/rmgpy/data/solvationTest.py", line 48, in testMcGowan
    soluteData = self.database.getSoluteData(species)
  File "/home/travis/build/GreenGroup/RMG-Py/rmgpy/data/solvation.py", line 589, in getSoluteData
    soluteData = self.getSoluteDataFromLibrary(species, self.libraries['solute'])
  File "/home/travis/build/GreenGroup/RMG-Py/rmgpy/data/solvation.py", line 637, in getSoluteDataFromLibrary
    return (deepcopy(entry.data), library, entry)
NameError: global name 'deepcopy' is not defined
======================================================================
ERROR: Test we can obtain solute parameters from a library
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GreenGroup/RMG-Py/rmgpy/data/solvationTest.py", line 27, in testSoluteLibrary
    libraryData = self.database.getSoluteDataFromLibrary(species, self.database.libraries['solute'])
  File "/home/travis/build/GreenGroup/RMG-Py/rmgpy/data/solvation.py", line 637, in getSoluteDataFromLibrary
    return (deepcopy(entry.data), library, entry)
NameError: global name 'deepcopy' is not defined
```

**Comment by nickvandewiele** [comment]
I'll fix this. I probably threw away too much.

**Comment by nickvandewiele** [comment]
I will replace remaining wild imports as well.

**Comment by nickvandewiele** [comment]
I removed pretty much all wild imports from the `rmgpy` package except from `rmgpy/measure` because I assumed it will soon become deprecated and some `\__init__.py` modules.

**Comment by nickvandewiele** [comment]
When (if) Travis passes successfully, I propose somebody merges this branch in master.

**Pull request merged**
